from enum import Enum


class CacheEntryState(Enum):
    """缓存条目状态"""

    VALID = "VALID"
    EXPIRED = "EXPIRED"
    REBUILDING = "REBUILDING"
    DEGRADED = "DEGRADED"


class RebuildStrategy(Enum):
    """缓存重建策略"""

    SYNC = "SYNC"
    ASYNC = "ASYNC"


DEFAULT_MAX_CACHE_SIZE = 10000
DEFAULT_TTL_SECONDS = 300
DEFAULT_JITTER_RATIO = 0.1
DEFAULT_HOT_KEY_THRESHOLD = 10
DEFAULT_HOT_KEY_WINDOW_SECONDS = 60
DEFAULT_REBUILD_TIMEOUT_SECONDS = 5
DEFAULT_BACKGROUND_RENEW_INTERVAL_SECONDS = 60
DEFAULT_DEGRADED_TTL_SECONDS = 10

REBUILD_LOCK_KEY_PREFIX = "__rebuild_lock__"
